name: Publish service
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: |
        wget https://github.com/tmijs/tmi.js/releases/download/v1.8.5/tmi.min.js
        git config user.email git@github.com
        git config user.name 'GitHub Actions'
        git add tmi.min.js
        git commit -m 'TMI download'
        git push -f -u origin master:gh-pages
